apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    {{- include "codeserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: code-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: code-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: code-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: code-config
          persistentVolumeClaim:
            claimName: code-config
      {{- end }}
      containers:
        - name: code-server
          image: avpc/code-server:{{ .Values.tag }}
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: "/config"
              name: code-config
          {{- end }}


