{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "codeserver.fullname" . }}
  labels:
    {{- include "codeserver.labels" . | nindent 4 }}
  annotations:
    {{- include "codeserver.annotations" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "codeserver.fullname" . }}
                port:
                  number: 80
{{- end }}
