apiVersion: v1
kind: Service
metadata:
  name: {{ include "codeserver.fullname" . }}
  labels:
    {{- include "codeserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: code-server
    app.kubernetes.io/instance: {{ .Release.Name }}
